<a href="https://colab.research.google.com/github/Hctor11/pytorch-for-deep-learning/blob/main/src/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

A torch tensor is a multi-dimensional matrix containing elements of a single data type. They are similar to numpy arrays but with the differencte that they work better with gpus.

Their default data type is float32 and they are more suitable for deep learning than numpy arrays.

In [1]:
import torch
import numpy as np

# Comparasion between numpy arrs and Tensors

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.32292394, 0.80685216, 0.96738636, 0.3022766 ],
       [0.30844929, 0.77830302, 0.12599373, 0.53224515],
       [0.80916566, 0.22824741, 0.13671357, 0.6250285 ]])

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.5150,  0.0560,  0.6421,  1.3687],
        [ 0.3140, -0.2438,  2.0371,  0.1641],
        [ 0.1117,  0.8020, -0.8901,  0.6484]])

In [5]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
# Create tensor out of numpy arr
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3229, 0.8069, 0.9674, 0.3023],
        [0.3084, 0.7783, 0.1260, 0.5322],
        [0.8092, 0.2282, 0.1367, 0.6250]], dtype=torch.float64)