<a href="https://colab.research.google.com/github/Hctor11/pytorch-for-deep-learning/blob/main/src/Tensors_math_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor math operations
- add, substract, multiply, divide, remainder and exponents.
- shorthands
- reassingment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_sum = tensor_a + tensor_b
tensor_sum

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Substraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [6]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [7]:
# Reassingment -----------------------------------------
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
tensor_a

tensor([ 6,  8, 10, 12])